---
title: "Homework5"
author: "Siyan Wen"
date: "2023-11-10"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)
library(ggplot2)

set.seed(1)
```

## Problem 1

```{r}

```

## Problem 2  
#### Dataframe 
```{r}
list_name<-
  as.list(
  list.files(path = "data",full.names = TRUE)
  )
# Test if list_name is a list
is.list(list_name)

file_name<-list.files(path = "data",full.names = FALSE)
```

```{r}
output <-
  list_name|>
  map_dfr(read_csv,.id = NULL)

file_info <- data.frame(file_name_ = file_name) |>
  mutate(subject_id = gsub(".*_(\\d+)\\.csv", "\\1",file_name_ ),
         arm = gsub("^(con|exp)_.*", "\\1",file_name_ ))

result_df <-
  bind_cols(file_info,output)|>
  select(-file_name_)|>
  pivot_longer(week_1:week_8,
    names_to ="Time",
    values_to ="Observation"
  )|>
  group_by(subject_id,arm)
```
#### Plot
```{r}
 ggplot(result_df, aes(x = Time, y = Observation, group=subject_id, color = subject_id)) +
  geom_line() +
  labs(title = "Spaghetti Plot of Observations by Subject Over Time", x = "Time", y = "Observation") +
  theme_minimal()+
  facet_wrap(~arm, nrow = 2)
```

```{r}
```

## Problem 3  

```{r}

```